/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoofingRouteImport } from './routes/roofing'
import { Route as FitnessRouteImport } from './routes/fitness'
import { Route as AgencyRouteImport } from './routes/agency'
import { Route as IndexRouteImport } from './routes/index'

const RoofingRoute = RoofingRouteImport.update({
  id: '/roofing',
  path: '/roofing',
  getParentRoute: () => rootRouteImport,
} as any)
const FitnessRoute = FitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencyRoute = AgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/fitness': typeof FitnessRoute
  '/roofing': typeof RoofingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/fitness': typeof FitnessRoute
  '/roofing': typeof RoofingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agency': typeof AgencyRoute
  '/fitness': typeof FitnessRoute
  '/roofing': typeof RoofingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agency' | '/fitness' | '/roofing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agency' | '/fitness' | '/roofing'
  id: '__root__' | '/' | '/agency' | '/fitness' | '/roofing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencyRoute: typeof AgencyRoute
  FitnessRoute: typeof FitnessRoute
  RoofingRoute: typeof RoofingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roofing': {
      id: '/roofing'
      path: '/roofing'
      fullPath: '/roofing'
      preLoaderRoute: typeof RoofingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitness': {
      id: '/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof FitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agency': {
      id: '/agency'
      path: '/agency'
      fullPath: '/agency'
      preLoaderRoute: typeof AgencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencyRoute: AgencyRoute,
  FitnessRoute: FitnessRoute,
  RoofingRoute: RoofingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
